name: Docker Compose CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Verify Docker Compose is available
        run: docker compose version

      - name: Copy environment file
        run: cp example.env .env

      - name: Build and start services
        run: docker compose -f ./docker-compose.yml up -d --build

      - name: Wait for services to initialize
        run: sleep 30

      - name: Show running containers
        run: docker ps

      - name: Shut down and clean up
        if: always()
        run: docker compose -f ./docker-compose.yml down -v
