name: Docker Compose CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        uses: docker/setup-docker-action@v2

      - name: Copy .env file
        run: cp example.env .env

      - name: Build and start services
        run: docker-compose up -d --build

      - name: Wait for services to be ready
        run: |
          echo "Waiting for services to be ready..."
          sleep 30

      - name: Check running containers
        run: docker ps

      - name: Tear down
        if: always()
        run: docker-compose down -v
