services:
  bc_python:
    build: 
      context: .
      dockerfile: ./bin/Dockerfile.python
    restart: "always"
    container_name: "${COMPOSE_PROJECT_NAME}-python"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DEBUG: ${DEBUG}
    volumes:
      - ./src:/app:rw
      - .env:/app/.env:ro
      - ./instructions.txt:/app/instructions.txt:ro
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:5000"
    networks:
      - connector
  bc_redis:
    image: redis:latest
    container_name: "${COMPOSE_PROJECT_NAME}-redis"
    restart: always
    ports:
      - "6379:6379"
    networks:
      - connector
  bc_mysql:
    build:
      context: .
      dockerfile: "./bin/Dockerfile.mysql"
    container_name: "${COMPOSE_PROJECT_NAME}-mysql"
    restart: "always"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: America/Los_Angeles
    command: --mysql-native-password=ON
    networks:
      - connector
  bc_phpmyadmin:
    image: phpmyadmin
    container_name: "${COMPOSE_PROJECT_NAME}-phpmyadmin"
    links:
      - bc_mysql
    environment:
      PMA_HOST: bc_mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      UPLOAD_LIMIT: ${UPLOAD_LIMIT}
      MEMORY_LIMIT: ${MEMORY_LIMIT}
    volumes:
      - /sessions
    networks:
      - connector
    ports:
      - "${PHPMYADMIN_PORT}:80"

networks:
  connector:
    driver: bridge
